# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.battlewinner_cannon.root] run return 0
execute on passengers if entity @s[tag=aj.battlewinner_cannon.data] unless data entity @s {data:{rigHash: '79ee9bbe01affe3b155f63af041ebddefae6fbc87e96b61b0b91340ffb9512e5'}} on vehicle run function animated_java:battlewinner_cannon/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1