# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.global.data] run function animated_java:battlewinner_cannon_base/animations/animation.cannon_base.default/zzz/frames/$(frame) with entity @s data.uuids
execute on passengers run data modify entity @s[tag=aj.global.data] start_interpolation set value -1
return 1