# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.battlewinner_cannon.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'battlewinner_cannon', 'function_path': 'animated_java:battlewinner_cannon/animations/animation.cannon.fire/play'}
tag @s add aj.battlewinner_cannon.animation.animation.cannon.fire.playing
scoreboard players set @s aj.animation.cannon.fire.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:battlewinner_cannon/animations/animation.cannon.fire/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only