# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.battlewinner_cannon_base.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'battlewinner_cannon_base', 'function_path': 'animated_java:battlewinner_cannon_base/animations/animation.cannon_base.default/next_frame'}
execute if score @s aj.animation.cannon_base.default.frame matches 2.. run scoreboard players set @s aj.animation.cannon_base.default.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.animation.cannon_base.default.frame
execute at @s run function animated_java:battlewinner_cannon_base/animations/animation.cannon_base.default/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.animation.cannon_base.default.frame 1