# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.battlewinner_cannon_ball.root] run return 0
execute on passengers if entity @s[tag=aj.battlewinner_cannon_ball.data] unless data entity @s {data:{rigHash: 'f70eaa08ab0c37873a9fe51ad1db081099ea5e13d9df7b377fe6b776bc7147fb'}} on vehicle run function animated_java:battlewinner_cannon_ball/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1