# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.battlewinner_cannon.node.blast] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.block_display_blast set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.battlewinner_cannon.node.middle] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.block_display_middle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.battlewinner_cannon.node.end] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.block_display_end set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.battlewinner_cannon.node.smoker] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.block_display_smoker set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.battlewinner_cannon.node.rotate_part2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.block_display_rotate_part2 set from storage aj:uuid main.out