# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(block_display_blast) {transformation: [-1.5f,0f,0f,0.75f,0f,1.5f,0f,0.75f,0f,0f,-1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_middle) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,1f,0f,0f,-1f,1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_end) {transformation: [-1.5f,0f,0f,0.75f,0f,1.5f,0f,0.75f,0f,0f,-0.6875f,1.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_smoker) {transformation: [1f,0f,0f,-0.5f,0f,0f,-1f,2f,0f,1f,0f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display_rotate_part2) {transformation: [-1f,0f,0f,0.5f,0f,0.75f,0f,0.25f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}