# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute at @n[tag=aj.battlewinner_cannon.node.smoker] run particle poof ~ ~1 ~ 0 0 0 1 64
execute at @n[tag=aj.battlewinner_cannon.node.smoker] run particle smoke ~ ~1 ~ 0 0 0 1 64
execute at @n[tag=aj.battlewinner_cannon.node.smoker] run particle lava ~ ~1 ~ 0 0 0 1 64