# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.battlewinner_cannon_base.root] run return 0
execute on passengers if entity @s[tag=aj.battlewinner_cannon_base.data] unless data entity @s {data:{rigHash: '6604add4a87b5129689c19e71046b20f8ab4e6ce60f9719ae7a29f17caf1a725'}} on vehicle run function animated_java:battlewinner_cannon_base/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1