# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.battlewinner_cannon_base.node.rotate_part] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.block_display_rotate_part set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.battlewinner_cannon_base.node.base] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.block_display_base set from storage aj:uuid main.out